(cl:in-package yuvaan_controller-msg)
(cl:export '(VEL_LINEAR_X-VAL
          VEL_LINEAR_X
          VEL_ANGULAR_Z-VAL
          VEL_ANGULAR_Z
          MODE-VAL
          MODE
          YAW_MODE-VAL
          YAW_MODE
          ROLL_MODE-VAL
          ROLL_MODE
          RA_1-VAL
          RA_1
          RA_2-VAL
          RA_2
          RA_3-VAL
          RA_3
          RA_4-VAL
          RA_4
          RA_5-VAL
          RA_5
          RA_6-VAL
          RA_6
          BA_1-VAL
          BA_1
          BA_2-VAL
          BA_2
          BA_3-VAL
          BA_3
          BA_4-VAL
          BA_4
          BA_5-VAL
          BA_5
          BA_6-VAL
          BA_6
))