# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yuvaan_controller/mani.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class mani(genpy.Message):
  _md5sum = "d4cb1b85a0be84892c13244d118cfb38"
  _type = "yuvaan_controller/mani"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 yaw_mode
int32 roll_mode
int32 ra_1
int32 ra_2
int32 ra_3
int32 ra_4
int32 ra_5
int32 ra_6"""
  __slots__ = ['yaw_mode','roll_mode','ra_1','ra_2','ra_3','ra_4','ra_5','ra_6']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       yaw_mode,roll_mode,ra_1,ra_2,ra_3,ra_4,ra_5,ra_6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mani, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.yaw_mode is None:
        self.yaw_mode = 0
      if self.roll_mode is None:
        self.roll_mode = 0
      if self.ra_1 is None:
        self.ra_1 = 0
      if self.ra_2 is None:
        self.ra_2 = 0
      if self.ra_3 is None:
        self.ra_3 = 0
      if self.ra_4 is None:
        self.ra_4 = 0
      if self.ra_5 is None:
        self.ra_5 = 0
      if self.ra_6 is None:
        self.ra_6 = 0
    else:
      self.yaw_mode = 0
      self.roll_mode = 0
      self.ra_1 = 0
      self.ra_2 = 0
      self.ra_3 = 0
      self.ra_4 = 0
      self.ra_5 = 0
      self.ra_6 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.yaw_mode, _x.roll_mode, _x.ra_1, _x.ra_2, _x.ra_3, _x.ra_4, _x.ra_5, _x.ra_6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.yaw_mode, _x.roll_mode, _x.ra_1, _x.ra_2, _x.ra_3, _x.ra_4, _x.ra_5, _x.ra_6,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8i().pack(_x.yaw_mode, _x.roll_mode, _x.ra_1, _x.ra_2, _x.ra_3, _x.ra_4, _x.ra_5, _x.ra_6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 32
      (_x.yaw_mode, _x.roll_mode, _x.ra_1, _x.ra_2, _x.ra_3, _x.ra_4, _x.ra_5, _x.ra_6,) = _get_struct_8i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8i = None
def _get_struct_8i():
    global _struct_8i
    if _struct_8i is None:
        _struct_8i = struct.Struct("<8i")
    return _struct_8i
