# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yuvaan_controller/unified_control.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class unified_control(genpy.Message):
  _md5sum = "4f2a61c6bf7b2e257f911489b14b7b6b"
  _type = "yuvaan_controller/unified_control"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Unified Control Message
# Combines drive control + 3 servos (1 D-pad + 2 analog stick)

# Drive control
int32 vel_linear_x    # Linear velocity (-255 to 255)
int32 vel_angular_z   # Angular velocity (-255 to 255)
int32 mode            # Drive mode (1=slow, 2=medium, 3=fast, 4=max)

# Servo control (all in microseconds, 1500=stop)
int32 servo_dpad      # D-pad controlled servo (1000-2000μs)
int32 servo_stick_x   # Right stick X servo (1000-2000μs)
int32 servo_stick_y   # Right stick Y servo (1000-2000μs)
"""
  __slots__ = ['vel_linear_x','vel_angular_z','mode','servo_dpad','servo_stick_x','servo_stick_y']
  _slot_types = ['int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vel_linear_x,vel_angular_z,mode,servo_dpad,servo_stick_x,servo_stick_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(unified_control, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vel_linear_x is None:
        self.vel_linear_x = 0
      if self.vel_angular_z is None:
        self.vel_angular_z = 0
      if self.mode is None:
        self.mode = 0
      if self.servo_dpad is None:
        self.servo_dpad = 0
      if self.servo_stick_x is None:
        self.servo_stick_x = 0
      if self.servo_stick_y is None:
        self.servo_stick_y = 0
    else:
      self.vel_linear_x = 0
      self.vel_angular_z = 0
      self.mode = 0
      self.servo_dpad = 0
      self.servo_stick_x = 0
      self.servo_stick_y = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.vel_linear_x, _x.vel_angular_z, _x.mode, _x.servo_dpad, _x.servo_stick_x, _x.servo_stick_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.vel_linear_x, _x.vel_angular_z, _x.mode, _x.servo_dpad, _x.servo_stick_x, _x.servo_stick_y,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.vel_linear_x, _x.vel_angular_z, _x.mode, _x.servo_dpad, _x.servo_stick_x, _x.servo_stick_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.vel_linear_x, _x.vel_angular_z, _x.mode, _x.servo_dpad, _x.servo_stick_x, _x.servo_stick_y,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6i = None
def _get_struct_6i():
    global _struct_6i
    if _struct_6i is None:
        _struct_6i = struct.Struct("<6i")
    return _struct_6i
