# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from yuvaan_controller/yuvaan.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class yuvaan(genpy.Message):
  _md5sum = "f9d9c81a204467304bb82823914c9c9d"
  _type = "yuvaan_controller/yuvaan"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 vel_linear_x
int32 vel_angular_z
int32 mode
int32 yaw_mode
int32 roll_mode
int32 ra_1
int32 ra_2
int32 ra_3
int32 ra_4
int32 ra_5
int32 ra_6
int32 ba_1
int32 ba_2
int32 ba_3
int32 ba_4
int32 ba_5
int32 ba_6"""
  __slots__ = ['vel_linear_x','vel_angular_z','mode','yaw_mode','roll_mode','ra_1','ra_2','ra_3','ra_4','ra_5','ra_6','ba_1','ba_2','ba_3','ba_4','ba_5','ba_6']
  _slot_types = ['int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vel_linear_x,vel_angular_z,mode,yaw_mode,roll_mode,ra_1,ra_2,ra_3,ra_4,ra_5,ra_6,ba_1,ba_2,ba_3,ba_4,ba_5,ba_6

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(yuvaan, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.vel_linear_x is None:
        self.vel_linear_x = 0
      if self.vel_angular_z is None:
        self.vel_angular_z = 0
      if self.mode is None:
        self.mode = 0
      if self.yaw_mode is None:
        self.yaw_mode = 0
      if self.roll_mode is None:
        self.roll_mode = 0
      if self.ra_1 is None:
        self.ra_1 = 0
      if self.ra_2 is None:
        self.ra_2 = 0
      if self.ra_3 is None:
        self.ra_3 = 0
      if self.ra_4 is None:
        self.ra_4 = 0
      if self.ra_5 is None:
        self.ra_5 = 0
      if self.ra_6 is None:
        self.ra_6 = 0
      if self.ba_1 is None:
        self.ba_1 = 0
      if self.ba_2 is None:
        self.ba_2 = 0
      if self.ba_3 is None:
        self.ba_3 = 0
      if self.ba_4 is None:
        self.ba_4 = 0
      if self.ba_5 is None:
        self.ba_5 = 0
      if self.ba_6 is None:
        self.ba_6 = 0
    else:
      self.vel_linear_x = 0
      self.vel_angular_z = 0
      self.mode = 0
      self.yaw_mode = 0
      self.roll_mode = 0
      self.ra_1 = 0
      self.ra_2 = 0
      self.ra_3 = 0
      self.ra_4 = 0
      self.ra_5 = 0
      self.ra_6 = 0
      self.ba_1 = 0
      self.ba_2 = 0
      self.ba_3 = 0
      self.ba_4 = 0
      self.ba_5 = 0
      self.ba_6 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_17i().pack(_x.vel_linear_x, _x.vel_angular_z, _x.mode, _x.yaw_mode, _x.roll_mode, _x.ra_1, _x.ra_2, _x.ra_3, _x.ra_4, _x.ra_5, _x.ra_6, _x.ba_1, _x.ba_2, _x.ba_3, _x.ba_4, _x.ba_5, _x.ba_6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 68
      (_x.vel_linear_x, _x.vel_angular_z, _x.mode, _x.yaw_mode, _x.roll_mode, _x.ra_1, _x.ra_2, _x.ra_3, _x.ra_4, _x.ra_5, _x.ra_6, _x.ba_1, _x.ba_2, _x.ba_3, _x.ba_4, _x.ba_5, _x.ba_6,) = _get_struct_17i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_17i().pack(_x.vel_linear_x, _x.vel_angular_z, _x.mode, _x.yaw_mode, _x.roll_mode, _x.ra_1, _x.ra_2, _x.ra_3, _x.ra_4, _x.ra_5, _x.ra_6, _x.ba_1, _x.ba_2, _x.ba_3, _x.ba_4, _x.ba_5, _x.ba_6))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 68
      (_x.vel_linear_x, _x.vel_angular_z, _x.mode, _x.yaw_mode, _x.roll_mode, _x.ra_1, _x.ra_2, _x.ra_3, _x.ra_4, _x.ra_5, _x.ra_6, _x.ba_1, _x.ba_2, _x.ba_3, _x.ba_4, _x.ba_5, _x.ba_6,) = _get_struct_17i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_17i = None
def _get_struct_17i():
    global _struct_17i
    if _struct_17i is None:
        _struct_17i = struct.Struct("<17i")
    return _struct_17i
