// Generated by gencpp from file yuvaan_controller/drive.msg
// DO NOT EDIT!


#ifndef YUVAAN_CONTROLLER_MESSAGE_DRIVE_H
#define YUVAAN_CONTROLLER_MESSAGE_DRIVE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yuvaan_controller
{
template <class ContainerAllocator>
struct drive_
{
  typedef drive_<ContainerAllocator> Type;

  drive_()
    : vel_linear_x(0)
    , vel_angular_z(0)
    , mode(0)  {
    }
  drive_(const ContainerAllocator& _alloc)
    : vel_linear_x(0)
    , vel_angular_z(0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef int32_t _vel_linear_x_type;
  _vel_linear_x_type vel_linear_x;

   typedef int32_t _vel_angular_z_type;
  _vel_angular_z_type vel_angular_z;

   typedef int32_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::yuvaan_controller::drive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yuvaan_controller::drive_<ContainerAllocator> const> ConstPtr;

}; // struct drive_

typedef ::yuvaan_controller::drive_<std::allocator<void> > drive;

typedef boost::shared_ptr< ::yuvaan_controller::drive > drivePtr;
typedef boost::shared_ptr< ::yuvaan_controller::drive const> driveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yuvaan_controller::drive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yuvaan_controller::drive_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yuvaan_controller::drive_<ContainerAllocator1> & lhs, const ::yuvaan_controller::drive_<ContainerAllocator2> & rhs)
{
  return lhs.vel_linear_x == rhs.vel_linear_x &&
    lhs.vel_angular_z == rhs.vel_angular_z &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yuvaan_controller::drive_<ContainerAllocator1> & lhs, const ::yuvaan_controller::drive_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yuvaan_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::drive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::drive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::drive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::drive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yuvaan_controller::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b1dd02d8c99c39b8457292a0b8bdd1a9";
  }

  static const char* value(const ::yuvaan_controller::drive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb1dd02d8c99c39b8ULL;
  static const uint64_t static_value2 = 0x457292a0b8bdd1a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::yuvaan_controller::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yuvaan_controller/drive";
  }

  static const char* value(const ::yuvaan_controller::drive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yuvaan_controller::drive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 vel_linear_x\n"
"int32 vel_angular_z\n"
"int32 mode\n"
;
  }

  static const char* value(const ::yuvaan_controller::drive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yuvaan_controller::drive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel_linear_x);
      stream.next(m.vel_angular_z);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yuvaan_controller::drive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yuvaan_controller::drive_<ContainerAllocator>& v)
  {
    s << indent << "vel_linear_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vel_linear_x);
    s << indent << "vel_angular_z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vel_angular_z);
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YUVAAN_CONTROLLER_MESSAGE_DRIVE_H
