// Generated by gencpp from file yuvaan_controller/drive_servo.msg
// DO NOT EDIT!


#ifndef YUVAAN_CONTROLLER_MESSAGE_DRIVE_SERVO_H
#define YUVAAN_CONTROLLER_MESSAGE_DRIVE_SERVO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yuvaan_controller
{
template <class ContainerAllocator>
struct drive_servo_
{
  typedef drive_servo_<ContainerAllocator> Type;

  drive_servo_()
    : vel_linear_x(0)
    , vel_angular_z(0)
    , mode(0)
    , servo_speed(0)  {
    }
  drive_servo_(const ContainerAllocator& _alloc)
    : vel_linear_x(0)
    , vel_angular_z(0)
    , mode(0)
    , servo_speed(0)  {
  (void)_alloc;
    }



   typedef int32_t _vel_linear_x_type;
  _vel_linear_x_type vel_linear_x;

   typedef int32_t _vel_angular_z_type;
  _vel_angular_z_type vel_angular_z;

   typedef int32_t _mode_type;
  _mode_type mode;

   typedef int32_t _servo_speed_type;
  _servo_speed_type servo_speed;





  typedef boost::shared_ptr< ::yuvaan_controller::drive_servo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yuvaan_controller::drive_servo_<ContainerAllocator> const> ConstPtr;

}; // struct drive_servo_

typedef ::yuvaan_controller::drive_servo_<std::allocator<void> > drive_servo;

typedef boost::shared_ptr< ::yuvaan_controller::drive_servo > drive_servoPtr;
typedef boost::shared_ptr< ::yuvaan_controller::drive_servo const> drive_servoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yuvaan_controller::drive_servo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yuvaan_controller::drive_servo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yuvaan_controller::drive_servo_<ContainerAllocator1> & lhs, const ::yuvaan_controller::drive_servo_<ContainerAllocator2> & rhs)
{
  return lhs.vel_linear_x == rhs.vel_linear_x &&
    lhs.vel_angular_z == rhs.vel_angular_z &&
    lhs.mode == rhs.mode &&
    lhs.servo_speed == rhs.servo_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yuvaan_controller::drive_servo_<ContainerAllocator1> & lhs, const ::yuvaan_controller::drive_servo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yuvaan_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::drive_servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::drive_servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::drive_servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::drive_servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::drive_servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::drive_servo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yuvaan_controller::drive_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f038d4ff1f38bef575d3a34d6c844c6d";
  }

  static const char* value(const ::yuvaan_controller::drive_servo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf038d4ff1f38bef5ULL;
  static const uint64_t static_value2 = 0x75d3a34d6c844c6dULL;
};

template<class ContainerAllocator>
struct DataType< ::yuvaan_controller::drive_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yuvaan_controller/drive_servo";
  }

  static const char* value(const ::yuvaan_controller::drive_servo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yuvaan_controller::drive_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Drive and Servo Control Message\n"
"# Combines differential drive control with continuous rotation servo control\n"
"\n"
"# Drive control\n"
"int32 vel_linear_x    # Linear velocity (-255 to 255)\n"
"int32 vel_angular_z   # Angular velocity (-255 to 255)\n"
"int32 mode            # Drive mode (1=slow, 2=medium, 3=fast, 4=max)\n"
"\n"
"# 360° Servo control (microseconds for precision)\n"
"int32 servo_speed     # Servo speed in microseconds (1000-2000, 1500=stop)\n"
;
  }

  static const char* value(const ::yuvaan_controller::drive_servo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yuvaan_controller::drive_servo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel_linear_x);
      stream.next(m.vel_angular_z);
      stream.next(m.mode);
      stream.next(m.servo_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct drive_servo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yuvaan_controller::drive_servo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yuvaan_controller::drive_servo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "vel_linear_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vel_linear_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_angular_z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vel_angular_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "servo_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.servo_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YUVAAN_CONTROLLER_MESSAGE_DRIVE_SERVO_H
