// Generated by gencpp from file yuvaan_controller/dual_servo.msg
// DO NOT EDIT!


#ifndef YUVAAN_CONTROLLER_MESSAGE_DUAL_SERVO_H
#define YUVAAN_CONTROLLER_MESSAGE_DUAL_SERVO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yuvaan_controller
{
template <class ContainerAllocator>
struct dual_servo_
{
  typedef dual_servo_<ContainerAllocator> Type;

  dual_servo_()
    : servo1_speed(0)
    , servo2_speed(0)  {
    }
  dual_servo_(const ContainerAllocator& _alloc)
    : servo1_speed(0)
    , servo2_speed(0)  {
  (void)_alloc;
    }



   typedef int32_t _servo1_speed_type;
  _servo1_speed_type servo1_speed;

   typedef int32_t _servo2_speed_type;
  _servo2_speed_type servo2_speed;





  typedef boost::shared_ptr< ::yuvaan_controller::dual_servo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yuvaan_controller::dual_servo_<ContainerAllocator> const> ConstPtr;

}; // struct dual_servo_

typedef ::yuvaan_controller::dual_servo_<std::allocator<void> > dual_servo;

typedef boost::shared_ptr< ::yuvaan_controller::dual_servo > dual_servoPtr;
typedef boost::shared_ptr< ::yuvaan_controller::dual_servo const> dual_servoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yuvaan_controller::dual_servo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yuvaan_controller::dual_servo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yuvaan_controller::dual_servo_<ContainerAllocator1> & lhs, const ::yuvaan_controller::dual_servo_<ContainerAllocator2> & rhs)
{
  return lhs.servo1_speed == rhs.servo1_speed &&
    lhs.servo2_speed == rhs.servo2_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yuvaan_controller::dual_servo_<ContainerAllocator1> & lhs, const ::yuvaan_controller::dual_servo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yuvaan_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::dual_servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::dual_servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::dual_servo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::dual_servo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::dual_servo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::dual_servo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yuvaan_controller::dual_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af2b50820dddbd7e357854376715f6d2";
  }

  static const char* value(const ::yuvaan_controller::dual_servo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf2b50820dddbd7eULL;
  static const uint64_t static_value2 = 0x357854376715f6d2ULL;
};

template<class ContainerAllocator>
struct DataType< ::yuvaan_controller::dual_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yuvaan_controller/dual_servo";
  }

  static const char* value(const ::yuvaan_controller::dual_servo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yuvaan_controller::dual_servo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Dual Servo Control Message\n"
"# Controls 2 servos independently using right analog stick\n"
"\n"
"int32 servo1_speed  # Servo 1 speed in microseconds (1000-2000, 1500=stop)\n"
"int32 servo2_speed  # Servo 2 speed in microseconds (1000-2000, 1500=stop)\n"
;
  }

  static const char* value(const ::yuvaan_controller::dual_servo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yuvaan_controller::dual_servo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo1_speed);
      stream.next(m.servo2_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct dual_servo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yuvaan_controller::dual_servo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yuvaan_controller::dual_servo_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "servo1_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.servo1_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "servo2_speed: ";
    Printer<int32_t>::stream(s, indent + "  ", v.servo2_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YUVAAN_CONTROLLER_MESSAGE_DUAL_SERVO_H
