// Generated by gencpp from file yuvaan_controller/mani.msg
// DO NOT EDIT!


#ifndef YUVAAN_CONTROLLER_MESSAGE_MANI_H
#define YUVAAN_CONTROLLER_MESSAGE_MANI_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yuvaan_controller
{
template <class ContainerAllocator>
struct mani_
{
  typedef mani_<ContainerAllocator> Type;

  mani_()
    : yaw_mode(0)
    , roll_mode(0)
    , ra_1(0)
    , ra_2(0)
    , ra_3(0)
    , ra_4(0)
    , ra_5(0)
    , ra_6(0)  {
    }
  mani_(const ContainerAllocator& _alloc)
    : yaw_mode(0)
    , roll_mode(0)
    , ra_1(0)
    , ra_2(0)
    , ra_3(0)
    , ra_4(0)
    , ra_5(0)
    , ra_6(0)  {
  (void)_alloc;
    }



   typedef int32_t _yaw_mode_type;
  _yaw_mode_type yaw_mode;

   typedef int32_t _roll_mode_type;
  _roll_mode_type roll_mode;

   typedef int32_t _ra_1_type;
  _ra_1_type ra_1;

   typedef int32_t _ra_2_type;
  _ra_2_type ra_2;

   typedef int32_t _ra_3_type;
  _ra_3_type ra_3;

   typedef int32_t _ra_4_type;
  _ra_4_type ra_4;

   typedef int32_t _ra_5_type;
  _ra_5_type ra_5;

   typedef int32_t _ra_6_type;
  _ra_6_type ra_6;





  typedef boost::shared_ptr< ::yuvaan_controller::mani_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yuvaan_controller::mani_<ContainerAllocator> const> ConstPtr;

}; // struct mani_

typedef ::yuvaan_controller::mani_<std::allocator<void> > mani;

typedef boost::shared_ptr< ::yuvaan_controller::mani > maniPtr;
typedef boost::shared_ptr< ::yuvaan_controller::mani const> maniConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yuvaan_controller::mani_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yuvaan_controller::mani_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yuvaan_controller::mani_<ContainerAllocator1> & lhs, const ::yuvaan_controller::mani_<ContainerAllocator2> & rhs)
{
  return lhs.yaw_mode == rhs.yaw_mode &&
    lhs.roll_mode == rhs.roll_mode &&
    lhs.ra_1 == rhs.ra_1 &&
    lhs.ra_2 == rhs.ra_2 &&
    lhs.ra_3 == rhs.ra_3 &&
    lhs.ra_4 == rhs.ra_4 &&
    lhs.ra_5 == rhs.ra_5 &&
    lhs.ra_6 == rhs.ra_6;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yuvaan_controller::mani_<ContainerAllocator1> & lhs, const ::yuvaan_controller::mani_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yuvaan_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::mani_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::mani_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::mani_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::mani_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::mani_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::mani_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yuvaan_controller::mani_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4cb1b85a0be84892c13244d118cfb38";
  }

  static const char* value(const ::yuvaan_controller::mani_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4cb1b85a0be8489ULL;
  static const uint64_t static_value2 = 0x2c13244d118cfb38ULL;
};

template<class ContainerAllocator>
struct DataType< ::yuvaan_controller::mani_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yuvaan_controller/mani";
  }

  static const char* value(const ::yuvaan_controller::mani_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yuvaan_controller::mani_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 yaw_mode\n"
"int32 roll_mode\n"
"int32 ra_1\n"
"int32 ra_2\n"
"int32 ra_3\n"
"int32 ra_4\n"
"int32 ra_5\n"
"int32 ra_6\n"
;
  }

  static const char* value(const ::yuvaan_controller::mani_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yuvaan_controller::mani_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yaw_mode);
      stream.next(m.roll_mode);
      stream.next(m.ra_1);
      stream.next(m.ra_2);
      stream.next(m.ra_3);
      stream.next(m.ra_4);
      stream.next(m.ra_5);
      stream.next(m.ra_6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mani_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yuvaan_controller::mani_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yuvaan_controller::mani_<ContainerAllocator>& v)
  {
    s << indent << "yaw_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yaw_mode);
    s << indent << "roll_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.roll_mode);
    s << indent << "ra_1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_1);
    s << indent << "ra_2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_2);
    s << indent << "ra_3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_3);
    s << indent << "ra_4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_4);
    s << indent << "ra_5: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_5);
    s << indent << "ra_6: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YUVAAN_CONTROLLER_MESSAGE_MANI_H
