// Generated by gencpp from file yuvaan_controller/unified_control.msg
// DO NOT EDIT!


#ifndef YUVAAN_CONTROLLER_MESSAGE_UNIFIED_CONTROL_H
#define YUVAAN_CONTROLLER_MESSAGE_UNIFIED_CONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yuvaan_controller
{
template <class ContainerAllocator>
struct unified_control_
{
  typedef unified_control_<ContainerAllocator> Type;

  unified_control_()
    : vel_linear_x(0)
    , vel_angular_z(0)
    , mode(0)
    , servo_dpad(0)
    , servo_stick_x(0)
    , servo_stick_y(0)  {
    }
  unified_control_(const ContainerAllocator& _alloc)
    : vel_linear_x(0)
    , vel_angular_z(0)
    , mode(0)
    , servo_dpad(0)
    , servo_stick_x(0)
    , servo_stick_y(0)  {
  (void)_alloc;
    }



   typedef int32_t _vel_linear_x_type;
  _vel_linear_x_type vel_linear_x;

   typedef int32_t _vel_angular_z_type;
  _vel_angular_z_type vel_angular_z;

   typedef int32_t _mode_type;
  _mode_type mode;

   typedef int32_t _servo_dpad_type;
  _servo_dpad_type servo_dpad;

   typedef int32_t _servo_stick_x_type;
  _servo_stick_x_type servo_stick_x;

   typedef int32_t _servo_stick_y_type;
  _servo_stick_y_type servo_stick_y;





  typedef boost::shared_ptr< ::yuvaan_controller::unified_control_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yuvaan_controller::unified_control_<ContainerAllocator> const> ConstPtr;

}; // struct unified_control_

typedef ::yuvaan_controller::unified_control_<std::allocator<void> > unified_control;

typedef boost::shared_ptr< ::yuvaan_controller::unified_control > unified_controlPtr;
typedef boost::shared_ptr< ::yuvaan_controller::unified_control const> unified_controlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yuvaan_controller::unified_control_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yuvaan_controller::unified_control_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yuvaan_controller::unified_control_<ContainerAllocator1> & lhs, const ::yuvaan_controller::unified_control_<ContainerAllocator2> & rhs)
{
  return lhs.vel_linear_x == rhs.vel_linear_x &&
    lhs.vel_angular_z == rhs.vel_angular_z &&
    lhs.mode == rhs.mode &&
    lhs.servo_dpad == rhs.servo_dpad &&
    lhs.servo_stick_x == rhs.servo_stick_x &&
    lhs.servo_stick_y == rhs.servo_stick_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yuvaan_controller::unified_control_<ContainerAllocator1> & lhs, const ::yuvaan_controller::unified_control_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yuvaan_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::unified_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::unified_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::unified_control_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::unified_control_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::unified_control_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::unified_control_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yuvaan_controller::unified_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f2a61c6bf7b2e257f911489b14b7b6b";
  }

  static const char* value(const ::yuvaan_controller::unified_control_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f2a61c6bf7b2e25ULL;
  static const uint64_t static_value2 = 0x7f911489b14b7b6bULL;
};

template<class ContainerAllocator>
struct DataType< ::yuvaan_controller::unified_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yuvaan_controller/unified_control";
  }

  static const char* value(const ::yuvaan_controller::unified_control_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yuvaan_controller::unified_control_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Unified Control Message\n"
"# Combines drive control + 3 servos (1 D-pad + 2 analog stick)\n"
"\n"
"# Drive control\n"
"int32 vel_linear_x    # Linear velocity (-255 to 255)\n"
"int32 vel_angular_z   # Angular velocity (-255 to 255)\n"
"int32 mode            # Drive mode (1=slow, 2=medium, 3=fast, 4=max)\n"
"\n"
"# Servo control (all in microseconds, 1500=stop)\n"
"int32 servo_dpad      # D-pad controlled servo (1000-2000μs)\n"
"int32 servo_stick_x   # Right stick X servo (1000-2000μs)\n"
"int32 servo_stick_y   # Right stick Y servo (1000-2000μs)\n"
;
  }

  static const char* value(const ::yuvaan_controller::unified_control_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yuvaan_controller::unified_control_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel_linear_x);
      stream.next(m.vel_angular_z);
      stream.next(m.mode);
      stream.next(m.servo_dpad);
      stream.next(m.servo_stick_x);
      stream.next(m.servo_stick_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct unified_control_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yuvaan_controller::unified_control_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yuvaan_controller::unified_control_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "vel_linear_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vel_linear_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_angular_z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vel_angular_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "servo_dpad: ";
    Printer<int32_t>::stream(s, indent + "  ", v.servo_dpad);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "servo_stick_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.servo_stick_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "servo_stick_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.servo_stick_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YUVAAN_CONTROLLER_MESSAGE_UNIFIED_CONTROL_H
