// Generated by gencpp from file yuvaan_controller/yuvaan.msg
// DO NOT EDIT!


#ifndef YUVAAN_CONTROLLER_MESSAGE_YUVAAN_H
#define YUVAAN_CONTROLLER_MESSAGE_YUVAAN_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yuvaan_controller
{
template <class ContainerAllocator>
struct yuvaan_
{
  typedef yuvaan_<ContainerAllocator> Type;

  yuvaan_()
    : vel_linear_x(0)
    , vel_angular_z(0)
    , mode(0)
    , yaw_mode(0)
    , roll_mode(0)
    , ra_1(0)
    , ra_2(0)
    , ra_3(0)
    , ra_4(0)
    , ra_5(0)
    , ra_6(0)
    , ba_1(0)
    , ba_2(0)
    , ba_3(0)
    , ba_4(0)
    , ba_5(0)
    , ba_6(0)  {
    }
  yuvaan_(const ContainerAllocator& _alloc)
    : vel_linear_x(0)
    , vel_angular_z(0)
    , mode(0)
    , yaw_mode(0)
    , roll_mode(0)
    , ra_1(0)
    , ra_2(0)
    , ra_3(0)
    , ra_4(0)
    , ra_5(0)
    , ra_6(0)
    , ba_1(0)
    , ba_2(0)
    , ba_3(0)
    , ba_4(0)
    , ba_5(0)
    , ba_6(0)  {
  (void)_alloc;
    }



   typedef int32_t _vel_linear_x_type;
  _vel_linear_x_type vel_linear_x;

   typedef int32_t _vel_angular_z_type;
  _vel_angular_z_type vel_angular_z;

   typedef int32_t _mode_type;
  _mode_type mode;

   typedef int32_t _yaw_mode_type;
  _yaw_mode_type yaw_mode;

   typedef int32_t _roll_mode_type;
  _roll_mode_type roll_mode;

   typedef int32_t _ra_1_type;
  _ra_1_type ra_1;

   typedef int32_t _ra_2_type;
  _ra_2_type ra_2;

   typedef int32_t _ra_3_type;
  _ra_3_type ra_3;

   typedef int32_t _ra_4_type;
  _ra_4_type ra_4;

   typedef int32_t _ra_5_type;
  _ra_5_type ra_5;

   typedef int32_t _ra_6_type;
  _ra_6_type ra_6;

   typedef int32_t _ba_1_type;
  _ba_1_type ba_1;

   typedef int32_t _ba_2_type;
  _ba_2_type ba_2;

   typedef int32_t _ba_3_type;
  _ba_3_type ba_3;

   typedef int32_t _ba_4_type;
  _ba_4_type ba_4;

   typedef int32_t _ba_5_type;
  _ba_5_type ba_5;

   typedef int32_t _ba_6_type;
  _ba_6_type ba_6;





  typedef boost::shared_ptr< ::yuvaan_controller::yuvaan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yuvaan_controller::yuvaan_<ContainerAllocator> const> ConstPtr;

}; // struct yuvaan_

typedef ::yuvaan_controller::yuvaan_<std::allocator<void> > yuvaan;

typedef boost::shared_ptr< ::yuvaan_controller::yuvaan > yuvaanPtr;
typedef boost::shared_ptr< ::yuvaan_controller::yuvaan const> yuvaanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yuvaan_controller::yuvaan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yuvaan_controller::yuvaan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yuvaan_controller::yuvaan_<ContainerAllocator1> & lhs, const ::yuvaan_controller::yuvaan_<ContainerAllocator2> & rhs)
{
  return lhs.vel_linear_x == rhs.vel_linear_x &&
    lhs.vel_angular_z == rhs.vel_angular_z &&
    lhs.mode == rhs.mode &&
    lhs.yaw_mode == rhs.yaw_mode &&
    lhs.roll_mode == rhs.roll_mode &&
    lhs.ra_1 == rhs.ra_1 &&
    lhs.ra_2 == rhs.ra_2 &&
    lhs.ra_3 == rhs.ra_3 &&
    lhs.ra_4 == rhs.ra_4 &&
    lhs.ra_5 == rhs.ra_5 &&
    lhs.ra_6 == rhs.ra_6 &&
    lhs.ba_1 == rhs.ba_1 &&
    lhs.ba_2 == rhs.ba_2 &&
    lhs.ba_3 == rhs.ba_3 &&
    lhs.ba_4 == rhs.ba_4 &&
    lhs.ba_5 == rhs.ba_5 &&
    lhs.ba_6 == rhs.ba_6;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yuvaan_controller::yuvaan_<ContainerAllocator1> & lhs, const ::yuvaan_controller::yuvaan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yuvaan_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::yuvaan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yuvaan_controller::yuvaan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::yuvaan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yuvaan_controller::yuvaan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::yuvaan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yuvaan_controller::yuvaan_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yuvaan_controller::yuvaan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9d9c81a204467304bb82823914c9c9d";
  }

  static const char* value(const ::yuvaan_controller::yuvaan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9d9c81a20446730ULL;
  static const uint64_t static_value2 = 0x4bb82823914c9c9dULL;
};

template<class ContainerAllocator>
struct DataType< ::yuvaan_controller::yuvaan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yuvaan_controller/yuvaan";
  }

  static const char* value(const ::yuvaan_controller::yuvaan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yuvaan_controller::yuvaan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 vel_linear_x\n"
"int32 vel_angular_z\n"
"int32 mode\n"
"int32 yaw_mode\n"
"int32 roll_mode\n"
"int32 ra_1\n"
"int32 ra_2\n"
"int32 ra_3\n"
"int32 ra_4\n"
"int32 ra_5\n"
"int32 ra_6\n"
"int32 ba_1\n"
"int32 ba_2\n"
"int32 ba_3\n"
"int32 ba_4\n"
"int32 ba_5\n"
"int32 ba_6\n"
;
  }

  static const char* value(const ::yuvaan_controller::yuvaan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yuvaan_controller::yuvaan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel_linear_x);
      stream.next(m.vel_angular_z);
      stream.next(m.mode);
      stream.next(m.yaw_mode);
      stream.next(m.roll_mode);
      stream.next(m.ra_1);
      stream.next(m.ra_2);
      stream.next(m.ra_3);
      stream.next(m.ra_4);
      stream.next(m.ra_5);
      stream.next(m.ra_6);
      stream.next(m.ba_1);
      stream.next(m.ba_2);
      stream.next(m.ba_3);
      stream.next(m.ba_4);
      stream.next(m.ba_5);
      stream.next(m.ba_6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct yuvaan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yuvaan_controller::yuvaan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yuvaan_controller::yuvaan_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "vel_linear_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vel_linear_x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vel_angular_z: ";
    Printer<int32_t>::stream(s, indent + "  ", v.vel_angular_z);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "yaw_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yaw_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "roll_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.roll_mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ra_1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ra_2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ra_3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ra_4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ra_5: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_5);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ra_6: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ra_6);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ba_1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ba_1);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ba_2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ba_2);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ba_3: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ba_3);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ba_4: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ba_4);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ba_5: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ba_5);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "ba_6: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ba_6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YUVAAN_CONTROLLER_MESSAGE_YUVAAN_H
